2020-04-22 10:25:12,538 ERROR: Exception on /search [GET] [in /home/julian/tawachai/venv/lib/python3.8/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/julian/tawachai/venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/julian/tawachai/venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/julian/tawachai/venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/julian/tawachai/venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/julian/tawachai/venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/julian/tawachai/venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/julian/tawachai/venv/lib/python3.8/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/julian/tawachai/app/main/routes.py", line 89, in search
    current_app.config['POSTS_PER_PAGE'])
KeyError: 'POSTS_PER_PAGE'
2020-04-22 10:27:18,514 INFO: tawachai startup [in /home/julian/tawachai/app/__init__.py:70]
2020-04-22 10:28:10,345 INFO: tawachai startup [in /home/julian/tawachai/app/__init__.py:70]
2020-04-22 10:29:49,540 INFO: tawachai startup [in /home/julian/tawachai/app/__init__.py:70]
2020-04-22 11:01:09,556 INFO: tawachai startup [in /home/julian/tawachai/app/__init__.py:75]
2020-04-22 11:01:20,600 INFO: tawachai startup [in /home/julian/tawachai/app/__init__.py:75]
2020-04-22 11:01:28,484 INFO: tawachai startup [in /home/julian/tawachai/app/__init__.py:75]
2020-04-22 11:08:42,135 INFO: tawachai startup [in /home/julian/tawachai/app/__init__.py:75]
2020-04-22 16:02:13,025 INFO: tawachai startup [in /home/julian/tawachai/app/__init__.py:75]
2020-04-22 16:02:16,822 ERROR: Exception on / [GET] [in /home/julian/tawachai/venv/lib/python3.8/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/julian/tawachai/venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/julian/tawachai/venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/julian/tawachai/venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/julian/tawachai/venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/julian/tawachai/venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/julian/tawachai/venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/julian/tawachai/venv/lib/python3.8/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/julian/tawachai/app/main/routes.py", line 34, in index
    page, current_app.config['PROJECTS_PER_PAGE'], False)
KeyError: 'PROJECTS_PER_PAGE'
2020-04-22 16:02:49,442 INFO: tawachai startup [in /home/julian/tawachai/app/__init__.py:75]
